Repository Moth-gang/Goonwood, pull requests merged in 2024-10, with the labels that each got.

#44 Повторная попытка добавить карту и возможность взаимодействовать мастер ключом с казначеской консолью
  _maps/map_files/rockhill_rus/rockhill_rus.dmm
  _maps/rockhill_rus.dm
  _maps/rockhill_rus.json
  code/datums/map_config.dm
  config/maps.txt
  modular_joparamble/code/_сode.dme
Labels: Mapping

#55 Фиксы
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  modular_joparamble/translate/code/emotes.dm
Labels: Balance

#56 Обнова бань
  _maps/map_files/rockhill_rus/rockhill_rus.dmm
Labels: Mapping

#58 фикс бань
  _maps/map_files/rockhill_rus/rockhill_rus.dmm
Labels: Mapping

#64 yay
  _maps/map_files/rockhill_ru/rockhill_ru.dmm
  _maps/map_files/rockhill_rus/rockhill_rus.dmm
Labels: Mapping

#61 handpies tastes fix (resolves #28)
  modular/Neu_Food/code/cooked/NeuFood_pies.dm
Labels: unmodular

#60 fix minor spelling mistake in dungeoneer.dm
  code/modules/jobs/job_types/roguetown/garrison/dungeoneer.dm
Labels: Balance, unmodular

#59 electrocution fix (siemens_coefficient in _gloves.dm)
  code/modules/clothing/gloves/_gloves.dm
Labels: unmodular
